config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home_page#index'

  resources :produce_items, only: %i[index]
  resources :item_seasons, only: %i[index show], param: :month_index

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item_season.rb
# frozen_string_literal: true

class ItemSeason < ApplicationRecord
  MONTHS = (1..12).to_a.freeze

  COUNTRIES = %w[BR].freeze
  enum coutry_code: COUNTRIES.index_by(&:to_sym)

  belongs_to :produce_item

  validates :month_index, :country_code, presence: true
end

# rubocop:disable Layout/LineLength
# == Schema Information
#
# Table name: item_seasons
#
#  id              :bigint           not null, primary key
#  month_index     :integer          not null
#  country_code    :string           not null
#  produce_item_id :bigint           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_item_seasons_on_produce_item_id  (produce_item_id)
#
# Foreign Keys
#
#  fk_rails_...  (produce_item_id => produce_items.id)
#
# rubocop:enable Layout/LineLength

app/models/produce_item.rb
# frozen_string_literal: true

class ProduceItem < ApplicationRecord
  CATEGORIES = %w[fruit vegetable green].freeze
  enum category: CATEGORIES.index_by(&:to_sym)

  has_many :item_seasons, dependent: :destroy

  validates :name, presence: true
  validates :category, presence: true
end

# rubocop:disable Layout/LineLength
# == Schema Information
#
# Table name: produce_items
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  category   :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_produce_items_on_name  (name) UNIQUE
#
# rubocop:enable Layout/LineLength

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
# frozen_string_literal: true

class HomePageController < ApplicationController
  def index; end
end

app/controllers/item_seasons_controller.rb
# frozen_string_literal: true

class ItemSeasonsController < ApplicationController
  before_action :set_item_season, only: %i[show]

  def index
    @item_seasons = ItemSeason.all
  end

  def show
    @item_season_produces = ProduceItem.joins(:item_seasons)
                                       .where(item_seasons: { month_index: @item_season.month_index })
  end

  private

  def set_item_season
    @item_season = ItemSeason.find_by(month_index: params[:month_index])
  end
end

app/controllers/produce_items_controller.rb
# frozen_string_literal: true

class ProduceItemsController < ApplicationController
  def index
    @produce_items = ProduceItem.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def formatted_month_name(month_index)
    I18n.t('date.month_names')[month_index]
  end

  def formatted_month_short(month_index)
    I18n.t('date.month_short')[month_index]
  end
end

app/helpers/item_seasons_helper.rb
# frozen_string_literal: true

module ItemSeasonsHelper
  def rotation(month_index)
    raise 'month-index must be between 1 and 12' if month_index > 12 || month_index < 1

    case month_index
    when 1, 6
      'rotate-plus-5'
    when 5
      'rotate-minus-5'
    when 12
      'rotate-plus-10'
    when 4, 9
      'rotate-minus-10'
    else
      'rotate-0'
    end
  end

  def month_navigation_previous(item_season)
    item_season.month_index == 1 ? 12 : item_season.month_index - 1
  end

  def month_navigation_next(item_season)
    item_season.month_index == 12 ? 1 : item_season.month_index + 1
  end
end

app/helpers/produce_items_helper.rb
# frozen_string_literal: true

module ProduceItemsHelper
  def formatted_month_list(produce)
    produce.item_seasons.order(month_index: :asc).map { formatted_month_name(_1.month_index) }.join(' / ')
  end
end

app/views/home_page/index.html.erb
<div class="content">
  <section class="banner-hero p-top-l p-bottom-l p-sides-m">
    <div class="script-md banner-hero__txt"><%= I18n.t('root.hero') %></div>
  </section>

  <section class="banner-buttons p-top-m p-bottom-l p-sides-m">
    <div class="p-bottom-m">
      <h3 class="color-yellow"><%= I18n.t('action.search_by') %></h3>
    </div>
    <div class="button-holder">
        <%= link_to I18n.t('action.month').capitalize, item_seasons_path, class: 'link_action button button--yellow script-lg rotate-minus-5' %>
        <%= link_to I18n.t('action.produce').capitalize, produce_items_path, class: 'link_action button button--yellow script-lg rotate-0' %>
    </div>
  </section>

  <section class="banner-about p-top-m p-bottom-l">
    <%= image_tag "https://dm2305files.storage.live.com/y4mYqMHpvb-2aKz6Q7P3jqr0EugNasCWn476P-zPwozPAPAxnKwadlz3S7DUa3FvDB2XLQdEI8rOvSkZTcITqKiIurRon4Fywldfm-p6DTsaNLzfXqXZUkFrkUVwxOswKTPKuMkElCHTjJZdNxSLwkr7bXSW3HyRvrI6J2MOl813zCFrm9YT9yP0pPecIaR9LZY?width=285&height=1217&cropmode=none", class: 'banner-about-img img-left' %>
    <div class="banner-about__txt">
      <div class="p-bottom-m">
          <h3 class="color-white"><%= I18n.t('root.about_title') %></h3>
      </div>
      <div>
        <p class="color-white p-bottom-m"><%= I18n.t('root.about_text_p1') %></p>
        <p class="color-white"><%= I18n.t('root.about_text_p2') %></p>
      </div>
    </div>
    <%= image_tag "https://dm2305files.storage.live.com/y4m9pwZq1iIqcdRBSt8VZEwJN6qA1UvxiiNXGFPETpPL4z08lKRDfpGUFuQ7CsrpYE0Vpou1Xgz-Gz4LcEd2mTKZyWSlfjXPzvinyXGo9SgxZwpiKxf6HWX6ui_Bn0s0uFQAd9Qxvccnz0ulEzPGQNW9CwIdfJtYP_89wi8HPn6ZdpqE9zWtZWO3GOMoJAwJgVF?width=269&height=1217&cropmode=none", class: 'banner-about-img img-right' %>
  </section>
</div>

app/views/home_page/show.html.erb
<h1><%= I18n.t('root.title') %></h1>
<h3><%= I18n.t('root.about') %></h3>

<p><%= link_to I18n.t('action.search_by_month').capitalize, item_seasons_path, class: 'link_action' %></p>
<p><%= link_to I18n.t('action.search_by_produce').capitalize, produce_items_path, class: 'link_action' %></p>

app/views/item_seasons/index.html.erb
<div class="content background-color-blue">
  <h1 class="page__title banner-small"> <%= I18n.t("item_season.index.title") %> </h1>

  <div class="button-holder p-top-l p-bottom-l p-sides-s">
    <% ItemSeason::MONTHS.each do |month_index| %>
      <%= link_to (formatted_month_short(month_index)), item_season_path(month_index),
            class: "link_action month_link button button--yellow script-lg m-top-s m-bottom-s #{rotation(month_index)}" %>
    <% end %>
  </div>
</div>

app/views/item_seasons/show.html.erb
<div class="content background-color-blue">
  <h1 class="page__title banner-small m-bottom-m"> <%= formatted_month_name(@item_season.month_index).capitalize %> </h1>

  <div class="nav-actions-holder p-sides-m">
    <h4><%= link_to I18n.t("action.back").upcase, item_seasons_path, class: "link_action back" %></h4>
    <div class="nav-actions-months">
      <%= link_to item_season_path(month_navigation_previous(@item_season)) do %>
        <i class="fa-solid fa-arrow-left-long" title="arrow-navigate-left" aria-hidden="true" aria-label="arrow-navigate-left"></i>
      <% end %>
      <h4 class="color-yellow p-sides-s"><%= I18n.t("action.month") %></h4>
      <%= link_to item_season_path(month_navigation_next(@item_season)) do %>
        <i class="fa-solid fa-arrow-right-long" title="arrow-navigate-right" aria-hidden="true" aria-label="arrow-navigate-right"></i>
      <% end %>
    </div>
  </div>

  <div class="card-holder p-top-l p-bottom-l p-sides-s">
    <% @item_season_produces.find_each do |produce| %>
      <div class="card">
        <div class="card-inner">
          <h4 class="produce-name"><%= link_to I18n.t("produce_items.names.#{produce.name}"), produce_items_path(anchor: produce.name), class: "link_action"  %></h4>
        </div>
          <div class="produce-category"><%= I18n.t("produce_items.categories.#{produce.category}") %></div>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProduceInSeason</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script async src="https://kit.fontawesome.com/e85e0c4e55.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.typekit.net/mxd1nlu.css">
  </head>

  <body>
    <% if notice %><div id="notice"><%= notice %></div><% end %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<h1><%= I18n.t('root.title') %></h1>
<h3><%= I18n.t('root.about') %></h3>

<p><%= link_to I18n.t('action.search_by_month').capitalize, item_seasons_path, class: "link_action" %></p>
<p><%= link_to I18n.t('action.search_by_produce').capitalize, produce_items_path, class: "link_action" %></p>

app/views/produce_items/index.html.erb
<div class="content background-color-blue">
  <h1 class="page__title banner-small m-bottom-m"> <%= I18n.t('produce_item.index.title') %> </h1>

  <div class="nav-actions-holder p-sides-m">
    <h4><%= link_to I18n.t("action.back").upcase, root_path, class: "link_action back" %></h4>
  </div>

  <div class="card-holder p-top-l p-bottom-l p-sides-s">
    <% @produce_items.find_each do |produce| %>
      <div class="card"  id="<%=produce.name%>">
        <div class="card-inner">
          <h4 class="produce-name"><%= I18n.t("produce_items.names.#{produce.name}") %></h4>
          <div class="card-inner__month-name">
            <%= formatted_month_list(produce) %>
          </div>
        </div>
          <div class="produce-category"><%= I18n.t("produce_items.categories.#{produce.category}") %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<section class="footer p-top-s p-bottom-s p-sides-m">
  <div class="logo">
    <%= I18n.t('footer.title') %>
  </div>
  <div class="nav-right">
    <%= mail_to "manu.vasconcelos@gmail.com", I18n.t('footer.contact'), class: 'link_action' %>
  </div>
</section>

app/views/shared/_navbar.html.erb
<section class="navbar p-top-s p-bottom-s p-sides-m">
  <div class="logo">
    <%= link_to t('nav.title_html'), root_path, class: 'link_action' %>
  </div>
  <div class="nav-right">
    <p>procure pelo</p>
    <%= link_to I18n.t('action.month'), item_seasons_path, class: 'link_action p-sides-s' %>
    <%= link_to I18n.t('action.produce'), produce_items_path, class: 'link_action' %>
  </div>
</section>